version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass mySecret123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "mySecret123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"  # Redis Insight Web UI
    volumes:
      - redisinsight_data:/db
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:mySecret123
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
  redisinsight_data: